[package]
name = "ton_client_node_js"
version = "1.1.2"
authors = ["TON Labs"]
license = "Apache-2.0"

[lib]
name = "tonclient"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
ton_client = {path = "../../client"}

#[dependencies.ton_client]
#path = "../../client"

[profile.release]
lto = true
